development:
  adapter: postgresql
  encoding: unicode
  database: basebox_development
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: basebox_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: basebox_production
  pool: 5